import pandas as pd
import numpy as np
from pandas.io.json import json_normalize


# df = pd.DataFrame({'A': [[0, 1, 2], 'foo', [], [3, 4]],
#                    'B': 1,
#                    'C': [['a', 'b', 'c'], np.nan, [], ['d', 'e']],
#                    'd': [['a', 'b', 'c'], np.nan, [], ['d', 'e']]
#                    })

df = pd.json_normalize({
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [ {
    "fullUrl": "1",
    "resource": {
      "resourceType": "Patient",
      "id": "8c95253e-8ee8-9ae8-6d40-021d702dc78e",
      "meta": {
        "profile": [ "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient" ]
      },
      "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: master-branch-latest\n .   Person seed: 8886041252665297312  Population seed: 13235</div>"
      },
      "extension": [ {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        "extension": [ {
          "url": "ombCategory",
          "valueCoding": {
            "system": "urn:oid:2.16.840.1.113883.6.238",
            "code": "2106-3",
            "display": "White"
          }
        }, {
          "url": "text",
          "valueString": "White"
        } ]
      }, {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
        "extension": [ {
          "url": "ombCategory",
          "valueCoding": {
            "system": "urn:oid:2.16.840.1.113883.6.238",
            "code": "2186-5",
            "display": "Not Hispanic or Latino"
          }
        }, {
          "url": "text",
          "valueString": "Not Hispanic or Latino"
        } ]
      }, {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
        "valueString": "Holley125 Champlin946"
      }, {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
        "valueCode": "M"
      }, {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
        "valueAddress": {
          "city": "Barnstable",
          "state": "Massachusetts",
          "country": "US"
        }
      }, {
        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
        "valueDecimal": 0.05826471038258488
      }, {
        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
        "valueDecimal": 52.94173528961741
      } ]}}]}
)


print(df)

df = df.explode("entry")
# df = df.json_normalize(df["entry"])


# df = df.explode('A')

print(df)