version: '3.3'

services:
  python:
    build: .
    ports:
      - "5000:5001"
    command: python3 ./python_file.py

  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - mysql_db_vol:/var/lib/mysql

volumes:
  mysql_db_vol: