version: '3.3'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'emis_test_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db_vol_1:/var/lib/mysql
    networks:
      pipeline_network:
        ipv4_address: 10.5.0.5

  python:
    container_name: python_pipline
    build: 
      context: ./
      dockerfile: dockerfile-python
    ports:
      - "5000:5001"
    networks:
      pipeline_network:
        ipv4_address: 10.5.0.6


volumes:
  mysql_db_vol_1:


networks:
  pipeline_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1